### ISSUE TITLE
Can't find libcufile.so.1

### ISSUE THREAD

**Issue by quasiben** [rapidsai/kvikio#140]
When trying to force the benchmark to run with GDS enabled I get the following error:

> KVIKIO_COMPAT_MODE=0 python benchmarks/single-node-io.py

```
Traceback (most recent call last):
  File "/home/quasiben/Github/kvikio/python/benchmarks/single-node-io.py", line 401, in <module>
    main(args)
  File "/home/quasiben/Github/kvikio/python/benchmarks/single-node-io.py", line 307, in main
    read, write = API[api](args)
  File "/home/quasiben/Github/kvikio/python/benchmarks/single-node-io.py", line 28, in run_cufile
    kvikio.memory_register(data)
  File "/home/quasiben/miniconda3/envs/kvikio_dev/lib/python3.9/site-packages/kvikio/__init__.py", line 13, in memory_register
    return libkvikio.memory_register(buf)
  File "libkvikio.pyx", line 44, in kvikio._lib.libkvikio.memory_register
RuntimeError: libcufile.so.1: cannot open shared object file: No such file or directory
````

I  just installed CUDA 11.8 and confirmed I have libcufile.so:

> /usr/local/cuda/lib64/libcufile.so -> libcufile.so.0

Additionally, during buliding kvikIO finds cuFILE:

```
cmake -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} ${CMAKE_EXTRA_ARGS} ..
-- The CXX compiler identification is GNU 9.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/quasiben/miniconda3/envs/kvikio_dev/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.8.89")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found cuFile: /usr/local/cuda/lib64/libcufile.so
-- Configuring done
```

Should we also search for libcufile.so in addition to libcufile.so.1 ?
> void* lib = load_library("libcufile.so.1");

**Comment by jakirkham** [comment]
Have we raised this with the GDS team offline?

**Comment by madsbk** [comment]
> Have we raised this with the GDS team offline?

Yes, they requirement using `libcufile.so.0` or `libcufile.so`. 
The problem with `libcufile.so` is that it might pick up a library stub.
