### ISSUE TITLE
Conda package isn't build with GDS support!

### ISSUE THREAD

**Issue by madsbk** [rapidsai/kvikio#378]
### Reproducer

```
mamba create -n kvikio-env -c rapidsai-nightly -c conda-forge python=3.11 cuda-version=12.2 kvikio
conda activate kvikio-env
pip install dask

# Run the benchmark with compatibility mode disabled, which forces KvikIO to use cuFile
KVIKIO_COMPAT_MODE=off python python/benchmarks/single-node-io.py
```
```
Roundtrip benchmark
----------------------------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   WARNING - cuFile compat mode   
         GDS not enabled          
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GPU               | Unknown (install pynvml)
GPU Memory Total  | Unknown (install pynvml)
BAR1 Memory Total | Unknown (install pynvml)
GDS driver        | N/A (Compatibility Mode)
GDS config.json   | /etc/cufile.json
----------------------------------
nbytes            | 10485760 bytes (10.00 MiB)
4K aligned        | True
pre-reg-buf       | True
directory         | /tmp/tmp71d24zvz
nthreads          | 1
nruns             | 1
==================================
Traceback (most recent call last):
  File "/home/mkristensen/repos/kvikio/python/benchmarks/single-node-io.py", line 429, in <module>
    main(args)
  File "/home/mkristensen/repos/kvikio/python/benchmarks/single-node-io.py", line 326, in main
    read, write = API[api](args)
  File "/home/mkristensen/repos/kvikio/python/benchmarks/single-node-io.py", line 47, in run_cufile
    res = f.write(data)
  File "/home/mkristensen/apps/miniforge3/envs/kvikio-env2404/lib/python3.10/site-packages/kvikio/cufile.py", line 261, in write
    return self.pwrite(buf, size, file_offset, task_size).get()
  File "/home/mkristensen/apps/miniforge3/envs/kvikio-env2404/lib/python3.10/site-packages/kvikio/cufile.py", line 33, in get
    return self._handle.get()
  File "libkvikio.pyx", line 25, in kvikio._lib.libkvikio.IOFuture.get
RuntimeError: KvikIO not compiled with cuFile.h
```

The latest version that works is `24.02`, the issue must have started somewhere between version `24.02` and `24.04`. 

cc. @aslobodaNV

**Comment by KyleFromNVIDIA** [comment]
KvikIO's `driver.hpp` has two different inline class definitions based on the value of `KVIKIO_CUFILE_FOUND`:

https://github.com/rapidsai/kvikio/blob/6ed7bccb42d82eb1ac60a98dfd460a7785881949/cpp/include/kvikio/driver.hpp#L43

https://github.com/rapidsai/kvikio/blob/6ed7bccb42d82eb1ac60a98dfd460a7785881949/cpp/include/kvikio/driver.hpp#L190-L272

The case where it's not defined throws the error we're seeing:

https://github.com/rapidsai/kvikio/blob/6ed7bccb42d82eb1ac60a98dfd460a7785881949/cpp/include/kvikio/driver.hpp#L204

CMake defines `KVIKIO_CUFILE_FOUND` appropriately:

https://github.com/rapidsai/kvikio/blob/6ed7bccb42d82eb1ac60a98dfd460a7785881949/cpp/CMakeLists.txt#L161

However, the Cython code bypasses anything built by CMake and includes `driver.hpp` directly:

https://github.com/rapidsai/kvikio/blob/6ed7bccb42d82eb1ac60a98dfd460a7785881949/python/kvikio/_lib/kvikio_cxx_api.pxd#L36

So it seems to me that we need to tell Cython to define `KVIKIO_CUFILE_FOUND`, but *only* if it's defined in the C++ code.

**Comment by KyleFromNVIDIA** [comment]
I can see now that KvikIO's exported CMake code is already setting this if cuFile is installed:

https://github.com/rapidsai/kvikio/blob/6ed7bccb42d82eb1ac60a98dfd460a7785881949/cpp/CMakeLists.txt#L132-L169

So we need to make sure cuFile is installed when the Python Conda package is built.

**Comment by vyasr** [comment]
The same error is also present [in the cufile shim code](https://github.com/rapidsai/kvikio/blob/branch-24.06/cpp/include/kvikio/shim/cufile_h_wrapper.hpp#L37), so it could be coming from there and not driver.hpp. Note that it is also possible for the version of `is_gds_enabled` in the cufile-enable branch of driver.hpp to return false [based on values produced by the cufile shim](https://github.com/rapidsai/kvikio/blob/branch-24.06/cpp/include/kvikio/driver.hpp#L87). Given that adding the libcufile package to the build env hasn't worked in #379 yet, those might be some additional things to check.

**Comment by madsbk** [comment]
Notice, `is_gds_enabled() == false` should not trigger the `RuntimeError: KvikIO not compiled with cuFile.h` error. It just means that cuFile will not use GDS acceleration.

**Comment by jakirkham** [comment]
Am going to reopen so we can track this fix as well

xref: https://github.com/rapidsai/kvikio/pull/381

**Comment by fstrug** [comment]
Hi, I think I might be running into a similar related error. I am installing kvikio with Conda and I can see the libcufile is installed in my environment. When I try to run the benchmark:

```
> KVIKIO_COMPAT_MODE=off python python/kvikio/kvikio/benchmarks/single_node_io.py 

Roundtrip benchmark
----------------------------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   WARNING - cuFile compat mode   
         GDS not enabled          
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GPU               | Unknown (install nvidia-ml-py)
GPU Memory Total  | Unknown (install nvidia-ml-py)
BAR1 Memory Total | Unknown (install nvidia-ml-py)
GDS driver        | N/A (Compatibility Mode)
GDS config.json   | /etc/cufile.json
----------------------------------
nbytes            | 10485760 bytes (10.00 MiB)
4K aligned        | True
pre-reg-buf       | False
directory         | /tmp/tmp4__41g_o
nthreads          | 1
nruns             | 1
==================================
Traceback (most recent call last):
  File "/home/fstrug/kvikio/python/kvikio/kvikio/benchmarks/single_node_io.py", line 375, in <module>
    main(args)
  File "/home/fstrug/kvikio/python/kvikio/kvikio/benchmarks/single_node_io.py", line 283, in main
    read, write = API[api](args)
                  ^^^^^^^^^^^^^^
  File "/home/fstrug/kvikio/python/kvikio/kvikio/benchmarks/single_node_io.py", line 45, in run_cufile
    f = kvikio.CuFile(file_path, flags="w")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fstrug/.conda/envs/img_cuda12.2-kvikio/lib/python3.12/site-packages/kvikio/cufile.py", line 88, in __init__
    self._handle = file_handle.CuFile(file, flags)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "file_handle.pyx", line 97, in kvikio._lib.file_handle.CuFile.__init__
RuntimeError: cuFile error at: /home/fstrug/.conda/envs/img_cuda12.2-kvikio/include/kvikio/file_handle.hpp:196: internal error
```

When trying to `cmake kvikio/cpp/examples/downstream/`, it is unable to find libcufile even though it is installed within the Conda environment.
```
(img_cuda12.2-kvikio) [fstrug@jupyter-fstrug build]$ cmake ..
-- The CXX compiler identification is GNU 11.4.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading CPM.cmake to /home/fstrug/kvikio/cpp/examples/downstream/build/cmake/CPM_0.35.5.cmake
-- CPM: adding package KvikIO@24.12 (branch-24.12)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- CPM: KvikIO: using local package CURL@7.87.0
-- Unable to find cublas_v2.h in either "/opt/conda/targets/x86_64-linux/include" or "/opt/conda/math_libs/include"
-- Found CUDAToolkit: /opt/conda/targets/x86_64-linux/include (found version "12.2.140") 
-- Could NOT find cuFile (missing: cuFile_INCLUDE_DIR) 
CMake Warning at build/_deps/kvikio-src/cpp/CMakeLists.txt:71 (message):
  Cannot find cuFile - KvikIO will still work but won't use GPUDirect Storage
  (GDS)


-- CPM: KvikIO: using local package nvtx3@3.1.0
-- CPM: KvikIO: using local package bs_thread_pool@4.1.0
-- Configuring done (4.6s)
-- Generating done (0.0s)
-- Build files have been written to: /home/fstrug/kvikio/cpp/examples/downstream/build
```

**Comment by jakirkham** [comment]
Can you please share `conda info` and `conda list`?

**Comment by fstrug** [comment]
Here are the outputs.

[conda_list.txt](https://github.com/user-attachments/files/17481208/conda_list.txt)
[conda_info.txt](https://github.com/user-attachments/files/17481209/conda_info.txt)

**Comment by jakirkham** [comment]
Thanks fstrung! 🙏

From a quick pass, those look reasonable

<hr>

In the build case expect we need to pass more arguments to `cmake` like

```bash
cmake .. \
    -DCMAKE_PREFIX_PATH="${CONDA_PREFIX}" \
    -DCMAKE_INSTALL_PREFIX:PATH="${CONDA_PREFIX}" \
    ...
;
```

Though we do have [`build.sh`]( https://github.com/rapidsai/kvikio/blob/fcf4b155314184e7f9ce1fa5209ca755a80a4867/build.sh ), which may help with that. So one could do the following to build and install the C++ and Python packages into your Conda env ([the install location can also be customized]( https://github.com/rapidsai/kvikio/blob/fcf4b155314184e7f9ce1fa5209ca755a80a4867/build.sh#L46-L49 ))

```bash
./build.sh libkvikio kvikio
```

<hr>

To your bigger question, think we should track this in a new issue. It certainly could be a packaging issue or it could also be some other library issue ( for example: https://github.com/rapidsai/kvikio/issues/497 ). Think we need to dive deeper. Would you be alright opening a new issue with the info you have provided here?

As a side note, it is possible to dump all the text info into it with using the pattern below, which may help as more folks look into it

```md
<details>

```bash
# Lots of output here
\```

</details>
```

**Comment by fstrug** [comment]
> In the build case expect we need to pass more arguments to `cmake` like
> 
> cmake .. \
>     -DCMAKE_PREFIX_PATH="${CONDA_PREFIX}" \
>     -DCMAKE_INSTALL_PREFIX:PATH="${CONDA_PREFIX}" \
>     ...
> ;
> 
> Though we do have [`build.sh`](https://github.com/rapidsai/kvikio/blob/fcf4b155314184e7f9ce1fa5209ca755a80a4867/build.sh), which may help with that. So one could do the following to build and install the C++ and Python packages into your Conda env ([the install location can also be customized](https://github.com/rapidsai/kvikio/blob/fcf4b155314184e7f9ce1fa5209ca755a80a4867/build.sh#L46-L49))

Unfortunately neither of these resolved the cuFile not found error. Passing the arguments to `cmake` gives the same output.

Building from source seemed to mostly work. Our systems drivers are version 12.2, so I've been trying to pin `cuda-version=12.2`. Perhaps there are some backwards compatibility issues, since we have encountered this ourselves when trying to set-up images with `cuda-version=12.6` and using `nvcc`. 

<details>

```bash
mamba env create --name kvikio-dev --file conda/environments/all_cuda-125_arch-x86_64.yaml
./build.sh libkvikio kvikio
```
it was able to find `cuFile` and for the test I get:

```bash
(kvikio-dev-clone) [fstrug@jupyter-fstrug kvikio]$ pytest python/kvikio/tests/
============================================================================================================================================= test session starts =============================================================================================================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/fstrug/kvikio/python/kvikio
configfile: pyproject.toml
plugins: cov-5.0.0
collected 1459 items                                                                                                                                                                                                                                                                                          

python/kvikio/tests/test_async_io.py .......                                                                                                                                                                                                                                                            [  0%]
python/kvikio/tests/test_basic_io.py .................................................................................................................................................................................................................................................................. [ 18%]
....................................................................................................................................................................................................................................................................................................... [ 38%]
............................................................................................................................s.......................................................................................................................................................................... [ 58%]
..................................................................ssssss.................................................................                                                                                                                                                               [ 67%]
python/kvikio/tests/test_benchmarks.py ............                                                                                                                                                                                                                                                     [ 68%]
python/kvikio/tests/test_defaults.py s....                                                                                                                                                                                                                                                              [ 69%]
python/kvikio/tests/test_examples.py ...                                                                                                                                                                                                                                                                [ 69%]
python/kvikio/tests/test_http_io.py .................................................                                                                                                                                                                                                                   [ 72%]
python/kvikio/tests/test_numpy.py ...........................                                                                                                                                                                                                                                           [ 74%]
python/kvikio/tests/test_nvcomp.py .......................xxxxxxXX.........x..xxx.........x........                                                                                                                                                                                                     [ 78%]
python/kvikio/tests/test_nvcomp_codec.py ................................................................................................................................................                                                                                                               [ 88%]
python/kvikio/tests/test_s3_io.py .....................................................................................                                                                                                                                                                                 [ 94%]
python/kvikio/tests/test_version.py .                                                                                                                                                                                                                                                                   [ 94%]
python/kvikio/tests/test_zarr.py .............................................................................                                                                                                                                                                                          [100%]

=========================================================================================================================== 1438 passed, 8 skipped, 11 xfailed, 2 xpassed in 41.28s ===========================================================================================================================

```

</details>
